version: "3"

services:
  weba:
    build:
      context: ./weba
    ports:
      - "8001:5000"
    volumes:
      - type: volume
        source: mfs_data
        target: /var/lib/mfs
    depends_on:
      - chunkserver1
      - chunkserver2
    # restart: always

  webb:
    build:
      context: ./webb
    ports:
      - "8002:5000"
    volumes:
      - type: volume
        source: mfs_data
        target: /var/lib/mfs
    depends_on:
      - chunkserver1
      - chunkserver2
    # restart: always
  mfsmaster:
    build: ./moosefs-master
    # image: moosefs/moosefs-master
    container_name: mfsmaster
    ports:
      - "9421:9421"
      - "9422:9422"
      - "9419:9419"
      - "9433:9433"
    volumes:
      - type: volume
        source: mfs_data
        target: /var/lib/mfs
    environment:
      - MFS_ENV=TEST 
      # In the TEST environment, if metadata.mfs file or other metadata files
      # like metdata.mfs.back and changelog.0.mfs are missing, the script will
      # create an EMPTY metadata file!
      # When MFS_ENV=PROD metdata.mfs file will not be created!

  chunkserver1:
    build: ./moosefs-chunkserver
    container_name: chunkserver1
    volumes:
      - type: volume
        source: mfs_data
        target: /data
    environment:
      - LABELS=M
      #- SIZE=100
    links:
      - mfsmaster
    depends_on:
      - mfsmaster
  chunkserver2:
    build: ./moosefs-chunkserver
    container_name: chunkserver2
    volumes:
      - type: volume
        source: mfs_data
        target: /data
    environment:
      - LABELS=M,B
      #- SIZE=100
    links:
      - mfsmaster
    depends_on:
      - mfsmaster

volumes:
  mfs_data:
